sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "8"
before_install:
  - npm i npm@^5 -g
script:
  - npm run build
  - npm run test-ci
after_success:
  - npm run report-coverage
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
notifications:
  email: false
